<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orders extends \Entities\Orders implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Orders' . "\0" . 'orderId', '' . "\0" . 'Entities\\Orders' . "\0" . 'shippingTypeId', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentTypeId', '' . "\0" . 'Entities\\Orders' . "\0" . 'userId', '' . "\0" . 'Entities\\Orders' . "\0" . 'addressId', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentId', '' . "\0" . 'Entities\\Orders' . "\0" . 'orderStatus', '' . "\0" . 'Entities\\Orders' . "\0" . 'orderDate', '' . "\0" . 'Entities\\Orders' . "\0" . 'deliveryDate', '' . "\0" . 'Entities\\Orders' . "\0" . 'total', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentKey', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentCode'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Orders' . "\0" . 'orderId', '' . "\0" . 'Entities\\Orders' . "\0" . 'shippingTypeId', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentTypeId', '' . "\0" . 'Entities\\Orders' . "\0" . 'userId', '' . "\0" . 'Entities\\Orders' . "\0" . 'addressId', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentId', '' . "\0" . 'Entities\\Orders' . "\0" . 'orderStatus', '' . "\0" . 'Entities\\Orders' . "\0" . 'orderDate', '' . "\0" . 'Entities\\Orders' . "\0" . 'deliveryDate', '' . "\0" . 'Entities\\Orders' . "\0" . 'total', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentKey', '' . "\0" . 'Entities\\Orders' . "\0" . 'paymentCode'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orders $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOrderId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOrderId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', []);

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingTypeId($shippingTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingTypeId', [$shippingTypeId]);

        return parent::setShippingTypeId($shippingTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTypeId', []);

        return parent::getShippingTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTypeId($paymentTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTypeId', [$paymentTypeId]);

        return parent::setPaymentTypeId($paymentTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTypeId', []);

        return parent::getPaymentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressId($addressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressId', [$addressId]);

        return parent::setAddressId($addressId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressId', []);

        return parent::getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentId($paymentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentId', [$paymentId]);

        return parent::setPaymentId($paymentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderStatus($orderStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderStatus', [$orderStatus]);

        return parent::setOrderStatus($orderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderStatus', []);

        return parent::getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderDate($orderDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderDate', [$orderDate]);

        return parent::setOrderDate($orderDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDate', []);

        return parent::getOrderDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryDate($deliveryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryDate', [$deliveryDate]);

        return parent::setDeliveryDate($deliveryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryDate', []);

        return parent::getDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentKey($paymentKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentKey', [$paymentKey]);

        return parent::setPaymentKey($paymentKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentKey', []);

        return parent::getPaymentKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentCode($paymentCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentCode', [$paymentCode]);

        return parent::setPaymentCode($paymentCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentCode', []);

        return parent::getPaymentCode();
    }

}
