<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Item extends \Entities\Item implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Item' . "\0" . 'itemId', '' . "\0" . 'Entities\\Item' . "\0" . 'manufacturerId', '' . "\0" . 'Entities\\Item' . "\0" . 'promotionId', '' . "\0" . 'Entities\\Item' . "\0" . 'categoryId', '' . "\0" . 'Entities\\Item' . "\0" . 'itemName', '' . "\0" . 'Entities\\Item' . "\0" . 'itemPrice', '' . "\0" . 'Entities\\Item' . "\0" . 'itemQuantity'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Item' . "\0" . 'itemId', '' . "\0" . 'Entities\\Item' . "\0" . 'manufacturerId', '' . "\0" . 'Entities\\Item' . "\0" . 'promotionId', '' . "\0" . 'Entities\\Item' . "\0" . 'categoryId', '' . "\0" . 'Entities\\Item' . "\0" . 'itemName', '' . "\0" . 'Entities\\Item' . "\0" . 'itemPrice', '' . "\0" . 'Entities\\Item' . "\0" . 'itemQuantity'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Item $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getItemId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getItemId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemId', []);

        return parent::getItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturerId($manufacturerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturerId', [$manufacturerId]);

        return parent::setManufacturerId($manufacturerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturerId', []);

        return parent::getManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionId($promotionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionId', [$promotionId]);

        return parent::setPromotionId($promotionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionId', []);

        return parent::getPromotionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryId($categoryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryId', [$categoryId]);

        return parent::setCategoryId($categoryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryId', []);

        return parent::getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemName($itemName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemName', [$itemName]);

        return parent::setItemName($itemName);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemName', []);

        return parent::getItemName();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemPrice($itemPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemPrice', [$itemPrice]);

        return parent::setItemPrice($itemPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemPrice', []);

        return parent::getItemPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemQuantity($itemQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemQuantity', [$itemQuantity]);

        return parent::setItemQuantity($itemQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemQuantity', []);

        return parent::getItemQuantity();
    }

}
