<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Userpayment extends \Entities\Userpayment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'paymentId', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'userId', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'cardName', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'creditCardNumber', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'securityNumber', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'expDate'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'paymentId', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'userId', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'cardName', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'creditCardNumber', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'securityNumber', '' . "\0" . 'Entities\\Userpayment' . "\0" . 'expDate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Userpayment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPaymentId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardName($cardName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardName', [$cardName]);

        return parent::setCardName($cardName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardName', []);

        return parent::getCardName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditCardNumber($creditCardNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditCardNumber', [$creditCardNumber]);

        return parent::setCreditCardNumber($creditCardNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCardNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCardNumber', []);

        return parent::getCreditCardNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecurityNumber($securityNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecurityNumber', [$securityNumber]);

        return parent::setSecurityNumber($securityNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecurityNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecurityNumber', []);

        return parent::getSecurityNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpDate($expDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpDate', [$expDate]);

        return parent::setExpDate($expDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpDate', []);

        return parent::getExpDate();
    }

}
